name: RandomFacts
version: '${project.version}'
main: me.grovre.randomfacts.RandomFacts
api-version: 1.18
authors: [ PoptartFromPluto ]
description: Randomly say facts
website: https://github.com/grovre
